baseURL = "https://core-aix.org/"
languageCode = "en-us"
title = "CORE-AIx"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[pagination]
  pagerSize = 6

[permalinks]
  blog = "/blog/:slug/"
  news = "/news/:slug/"

[params]
  lab_name = "CORE-AIx"
  lab_full_name = "Collaborative, optimized, reliable, efficient next generation AI at Exeter"
  tagline = "Collaborative, optimized, reliable, efficient next generation AI at Exeter."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "Research"
  url = "/research/"
  weight = 15

[[menu.main]]
  name = "News"
  url = "/news/"
  weight = 20

[[menu.main]]
  name = "Blogs"
  url = "/blog/"
  weight = 30

[[menu.main]]
  name = "People"
  url = "/people/"
  weight = 40

[[menu.main]]
  name = "Publications"
  url = "/publications/"
  weight = 50

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 60
